services:
    udt_web:
        container_name: udt_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "3000:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - udt_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - os-network  # Connect to the custom network

    udt_app:
        container_name: udt_app
        build: .  # Build from the Dockerfile
        depends_on:
            - udt_db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - os-network  # Connect to the custom network

    udt_db:
        container_name: udt_db
        image: mysql:8  # Use MySQL image
        restart: always
        ports:
            - "33010:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Set the root password for MySQL
        volumes:
            - udt_db:/var/lib/mysql  # Persist MySQL data
        networks:
            - os-network  # Connect to the custom network

networks:
    os-network:  # Create a custom network named 'os-network'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    udt_db:
